---
title: "My english activity log"
---

## Films, series

+ October 2019:  The Impossible, Me before you
+ November 2019: Joker 
+ February 2020: Lucifer (the netflix serie)
+ March 2020: Lucifer 
+ April 2020: 
  
## Books

+ November 2019: Game of thrones (volume 1)
+ December 2019: Game of thrones (volume 1 and 2)
+ February 2020: Game of thrones (volume 3)
+ March 2020: Game of thrones (volume 4 and the first pages of the 5)

## Newspapers

+ November 2019: The Guardian : some articles about the Brexit 
+ April 2020: The Guardian : an article about the spread of coronavirus in England

## Youtube/ Videos 

+ October 2019: some podcasts and several animal documentaries (BBC earth)
+ November 2019: Videos of the science channel "Kurzgesagt – In a Nutshell" : Bacteriophage, wormholes,...; Review of the movie Joker; Theories on the universe of the dark souls game. 
+ December 2019: Videos of the science channel "Kurzgesagt – In a Nutshell": vaccines, deep see,... 
+ January 2020: Podcasts, documentaries about the cancer 
+ February 2020: A let's play on the game "Bendy and the Ink machine", several animal documentaries (BBC earth), surgical operation descriptions, Podcasts 
+ March 2020: Some scientifics videos, podcasts
+ April 2020: a lot of animal/medical documentaries (Spiders, liver diseases, the greats epidemics, ants, the Amazonian forest ,...)


## Video games (voices and texts in english) 

+ October 2019: Dark souls 3 and skyrim
+ November 2019: Dark souls 3
+ December 2019: Dark souls 3 
+ February 2020: Assassin's creed black flag 
+ March 2020: AC black flag

  
## Mangas/animes (translated in english)

+ October 2019: Hunter x hunter, Jojo's bizarre adventure (seasons 1-2-3)
+ November 2019: Jojo's bizarre adventure (seasons 4-5), One punch man (season 2)
+ February 2020: One piece (season 2-3)
+ March 2020: Berserk 
+ April 2020: Boku no hero academia (last season)
  
## Others 

Throughout the school year, I have been conversing with English-speaking friends and regularly chatting in internet groups entirely in English. 


  
